apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: sadokdiba/my-web-app:latest  # or <aws_account_id>.dkr.ecr.us-west-1.amazonaws.com/my-web-app:latest
        ports:
        - containerPort: 8080
